name: New Monthly Build

'on':
  workflow_dispatch: null
  schedule:
    - cron: 15 1 1 * *

jobs:

  update-data-set:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: '${{ steps.composer-cache.outputs.dir }}'
          key: '${{ runner.os }}-composer-${{ hashFiles(''**/composer.lock'') }}'
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extension: >-
            dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite,
            bcmath, soap, intl, gd, exif, iconv, imagick
          ini-values: pcov.directory=app
          coverage: pcov

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Copy environment files
        run: cp .env.example .env

      - name: Generate app key
        run: 'php artisan key:generate'

      - name: Fetch download numbers for last month
        run: 'php artisan app:fetch-downloads'

      - name: Create new HTML Export
        run: php artisan export

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Data Set
          branch: master
